model: PosMLP
model_cfg: configs/models/PosMLP.yaml
save_dir:

num_classes: 2
num_seg: 8
dataset: TSNDataset
data_trans: fight_tsm_rgb
modality: RGB
num_workers: 8
input_size: 224
data_params:
  root_path: /media/sfy/disk1/dataset/Fight
  train_list: fight_train.txt
  val_list: fight_val.txt
  image_tmpl: '{:05d}.jpg'
  dense_sample: False
  clip_len: 64
  new_length: 1
  num_sample: 1
  twice_sample: False

train:
  enable: True
  pretrained: False
  optimizer: AdamW
  optim_params:
    lr: 4e-4
    betas: [0.9, 0.999]
    weight_decay: 1e-8

  scheduler: CosineAnnealingLR
  scheduler_params:
    T_max: 100
    eta_min: 1e-6

  loss: crossentropyloss
  epochs: 100
  batchsize: 16
  resume: False
  resume_path:

val:
  enable: False

test:
  enable: False