backbone:
  - [ -1, 1, nn.Linear, [3072, 1024] ]
  - [ -1, 1, nn.ReLU, [] ]
  - [ -1, 1, nn.Dropout, [0.5] ]
  - [ -1, 1, nn.Linear, [1024, 512] ]
  - [ -1, 1, nn.ReLU, [] ]
  - [ -1, 1, nn.Dropout, [0.5] ]
head:
  - [ -1, 1, nn.Linear, [512, 10] ]