
backbone:
  - [ -1, 1, PatchEmbed, [3, 72] ]
  - [ -1, 3, PermutatorBlock, [72, 8, 14, 8, 0] ]  # dim, gamma, size_s, size_t, drop_path, drop_rate=0., act=nn.GELU
  - [ -1, 1, Downsample, [72, 144] ]
  - [ -1, 4, PermutatorBlock, [144, 16, 14, 8, 0.02] ]
  - [ -1, 1, Downsample, [144, 288] ]
  - [ -1, 9, PermutatorBlock, [288, 32, 14, 8, 0.06] ]
  - [ -1, 1, Downsample, [288, 576] ]
  - [ -1, 3, PermutatorBlock, [576, 64, 7, 8, 0.1] ]
  - [ -1, 1, ReshapeForLN, [] ]
  - [ -1, 1, nn.LayerNorm, [576] ]
  - [ -1, 1, Mean, [1] ]
head:
  - [ -1, 1, nn.Linear, [576, 2] ]